apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remediador
  template:
    metadata:
      labels:
        app: remediador
    spec:
      serviceAccountName: remediador
      containers:
        - name: remediador
          image: ghcr.io/roger-macedo-dev/sentinel-remediador:v1
          env:
            - name: DRY_RUN
              value: "false"
            - name: ALLOWLIST
              value: "sidecar,api"
            - name: COOLDOWN_SEGUNDOS
              value: "600"
            - name: NAMESPACE
              value: "default"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: remediador
spec:
  selector:
    app: remediador
  ports:
    - port: 8080
      targetPort: 8080
