apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar
  template:
    metadata:
      annotations:
        config-checksum: "inicial"
      labels:
        app: sidecar
    spec:
      containers:
        - name: sidecar
          image: ghcr.io/roger-macedo-dev/sentinel-sidecar:v1
          ports:
            - containerPort: 8000
          env:
            - name: PROMETHEUS_URL
              value: "http://prometheus:9090"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: sidecar-config
---
apiVersion: v1
kind: Service
metadata:
  name: sidecar
spec:
  selector:
    app: sidecar
  ports:
    - port: 8000
      targetPort: 8000
