apiVersion: v1
kind: ServiceAccount
metadata:
  name: remediador
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remediador
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: remediador
subjects:
  - kind: ServiceAccount
    name: remediador
roleRef:
  kind: Role
  name: remediador
  apiGroup: rbac.authorization.k8s.io
